sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rTYkcB7CjmUJC4tS2De4f7mCB4i8TOXFJmx4r0LcRyVhOlLP5jNlnA4/kz1E9B8JYOQCNBQpbH/8pOsW1Q4E52PZDmRBurpcHbNcIObEz5+QmhvKkOHOoX6zZpWChIIHZYsWSXyVcAvLXAA06oHKxCmnwNQyaeuE2SaA9bPeX+zyg22JISn+UlR80R6+TKcSUJSCJ91TJqA1PVCChwQbMVGTY06MOgPuyS6eFZr2HfZWB9E9A1mwXH2wAkKgmg3aiyGOFNzqzAUbPgrgBxIu9U2NHxyzZdu1BSybN/6we7yYvfLFWwcqSmqVJS9wSWfCEaLw93cC8d8qOF9g8kfOa+CDfTtin1DXQ7uTLYzNhEL9zB9TKS4C6HGLSIIi8McOHSI88o48XauojPb6Ve3t4npFP/Y9MpHv5QHtozyTi8nDlvXWIyPr1tEIJYPjnglMDVIQzOOfkv+FefG4hCVyTRO5TChkNx45tM8Bd/6/v4ESWCDvYDu+bzcGGLb5SlqSILII1RZ+tj/nJ7pY8VYaOrq/aAPV4XT2W6CADk9049YO9ZFHJOo+wc2AFSSzteUPM6geANIKAPunOEP/0wz7TFZZPcsQUiYdyN4kArg/tNzp7xSCcukTvzYHn4HSoCuxK5JixUzoz3k4/bL08WwodwpDm7Mqd6DfySXblDDWGHo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Law-and-the-Lady_1622
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy